var words = [
	['forged', 'crafted', 'ethically produced', 
	'fabricated', 'fashioned', 'designed', 'produced', 
	'hand crafted', 'lovingly', 'transcribed','built from the ground up', 
	'hand finished', 'manufactured', 'shaped from earthen clay', 'carved', 'bound to this plane', 
	'pressed', 'tethered to this reality', 'assembled', 'put together', 'created', 'brought to you by', 
	'made', 'perfectly executed', 'falsified', 'concocted', 'activated', 'arose', 'incepted', 'harvested', 
	'ethically harvested', 'grown', 'attained', 'consummated', 'sewn together', 'materialized', 
	'hastily cobbled together', 'realized, brought to pass', 'acquired', 'delivered from God', 
	'perfected', 'procured', 'foraged', 'realized', 'brought to you by your local community', 
	'ripped from the ether', 'dug out from the ground', 'contractually obtained in the divorce', 
	'dreamt up by sirens', 'cut from the stone', 'won in a bar fight', 'found in a roadside ditch', 
	'bought at the dollarstore and repurposed', 'tamed from the unknowable wilds', 'thawed from the permafrost', 
	'found in an old church', 'ripped from the cold hands of the deceased', 'won in a bet', 
	'dredged from Lake Ontario', 'coughed up from the throat of an old cat', 'waken from its slumber'],
	['picturesque Picton Ontario', 'the scenic East Coast', 'the tome of an ancient God', 'the alley behind Ossington and Bloor',
	 'a mountain pass',' a fertile gully', 'a beach far away from here', 'my grandmother’s kitchen', 'on top a hillside',
	  'in the depths of a coal mine', 'a beautiful forest', 'Yonge and Dundas', 'Bloor station', 'Spadina station', 
	  'Kensington market', 'in the Annex',' entranceway of my part time job',' the St. Lawrence Market',' in your local bar',
	  'your local convenience store', 'the same place you made your biggest regret', 'the middle of the road', 
	  'the building you always look into on your walk to work', 'your old elementary school', 'the Eaton’s Centre', 
	  'the shortcut through the construction site', 'deep Scarborough', 'Union Go Train Station', 'the Beaches', 
	  'in your friend’s living room', ' Dufferin station', 'the AGO', 'your own home', 'the bathroom',
	 'your friends bathroom', 'in your bathroom', 'your office', 'a back alley', 'the bath', 'the shadow of Casa Loma',
	  'the water',' on the beach', 'Dufferin Mall', 'a truck stop', 
	  'an OnRoute station though which one I can’t be sure- they all look the same to me', 
	 ' your childhood home', 'the fanciest condo on the block', 'a 1970’s highrise', 'your living room', 'your bedroom', 
	  'the holiday market', 'the local hole in the wall', 'at your elementary school', 'Northern Ontario', 
	  'Peterborough', 'Ottawa', 'the bus station in Montreal', 'the walk in freezer of your favourite restaurant', 
	  'a forgotten part of the city', 'a dark basement',' a vineyard you can’t afford', 'the backwoods', 
	 ' a ritual space so secret it doesnt even exist', 'Shoppers Drugmart',' the closest Rexall '],
	['a crew of queer truckers', 'elves', 'talking animals', 'grizzled old men with nothing left to loose', 
	'the tiny bird hands of sparrows', 'your uncle', 'your mother', 'your father', 'your best friend',
	 'your greatest enemy', 'a talking tree', 'a small child working in their spare time to escape the cruel hand of capitalism', 'the cruel hand of capitalism',
	  'The Merchants Guild', 'a tech-bro in his spare time between start up gigs', 'a millennial', 
	  'an unassuming grandmother', 'a cloaked stranger',' a puckish rogue', 'a thousand children chanting ILLUMINATI CONFIRMED in unison',
	   'seven sisters', 'a dog', 'former lover', 
	   'your best friend', 'a lonely stranger', 'your boss', 'a creature made of mist', 
	   'the angriest hedgehog you’ve ever seen', ' the universe itself', 'a Swamp Thing', 
	   'a formless mass', 'a wandering storyteller',' a fiddler', 'a siren', 'a werewolf', 'a witch', 'the concept of dreams', 
	   'the unknowable', 'a metal cover band', 'a ska band', 
	   'the person who has basically the same schedule as you so you see them at the bus stop all the time', 
	   'a whirlwind', 'a monster made of your greatest fears', 'the fading sense of control you have on your life',
	     'a bear speaking tongues', 'a trash panda', 'your first date', 'Beyonce',
	     'a creeping sense of unattainable joy', 'the person you imagined yourself youd become when you were 9', 
	     'a human skull from the dollar store', 
	      'the man from the corner store', 'the person who you admire most', 
	     'all known human knowledge',  'a literal train', 'Guillermo del Toro', 'your middle school math teacher', 
	     'a toddler', 'an old man offering you a sword',' the boundlessness of the eternal void', 
	     'entirely formless fear',' literal garbage', 'the inevitable heat death of the universe', 'the reaching hand of Satan', 
	     'the answer to life the universe and everything', 'happiness', 'a man attempting to swallow a river', 
	      'a newborn baby', 'your landlord', 'the bartende'], 
	['rusty','angry', 'anxious', 'boring', 'creepy', 'embarrassing', 'lonely', 'mysterious', 'thoughtless', 'calming', 
	'gentle', 'overwhelming', 'citrusy', 'woody', 'mouldy', 'smokey' ],

	[
	                  'a handknit sweater', 'a handful of pink yarn', 
	                  'a hot bowl of soup from Food Not Bombs', 'a shirt your ex left behind but it’s been too long to give back without it getting weird which makes you both too upset to keep or dispose of', 
	                  'a really old looking pigeon',  'fresh of wood shavings',' a whittled toy sword', 
	                  'what appears to be a sack of runes', 'a vial of ink',  'a break from your worries',
	                  'a metaphorical mountain', 'a bunch of iron shaving',  
	                  'a bag full of your personal toenail clippings', 'one of those CPR practice dummies', 'a good book', 
	                  'an old book that’s missing its front cover',
	                  'a piece of ice from the back of the freezer', 'a broken promise', 'one of those friendship necklaces from Claire’s', 
	                   'a contract outlining the inheritance of a debt consisting of twelve seagulls and a chop saw', 
	                   ' Motorola Razr phone in pink',
	                    'everything you’d need for or want from a human sacrifice',  'a half used bottle of adhesive', 
	                    'fresh blueberries from up north', 'the last strawberry', 'that one fork you have that you hate using', 
	                   'whatever is behind door number 7', 
	                   'a fresh pack of cigarettes', 'an industrial bottle of lube', 'a single use hand warmer pack from the bottom of your backpack', 
	                   'a start-up company founded on the concept of free labour', 'the death rattle of capitalism', 
	                    'a bottle of cheap gin', 'a clock set fifteen minutes too fast', 

	                   
	                   'a scarf from a tourist shop',  'your high school transcript',
	                   'your second grade report card', 'all the hair ties you lost behind the couch',
	                   'one of those premixed spice packages', 
	                   'the nostalgia you feel for a time you never lived in', 'the looming stink of the unemptied trash can',
	                   'a fucking laser gun', 'Baba Yaga riding in on her cauldron ', 
	                   'the song your mother sung to you before you knew how to make memories', 'a lose-lose situation', 
	                   'a single lightbulb swinging in an empty room', 'an overgrown houseplant', 'your landlord',
						 'the first snow', 'your collection of unfinished notebooks',
	                           'an old analogue phone', 'a human heart',' a pumpkin pie', 'a single mouse you can hear in the walls on lonely nights',
	                     'beach filled with garbage',  'a black hole', 'the 504 streetcar','a grease fire', 'the moment between sunset and twilight', 'the best day of your life (yet)', 
	                     'sacrificing your first born to the Old Gods',  'that box you never unpack every time you move', 
	                      'that feeling of unrequited friendship',' a queer crush', 'a burnt cup of coffee at an event with a long line',
	                      'a youtube video playlist of every episode of How It’s Made'],
	['well calibrated berometers','fruit juice','a former lover', 'a stranger',
	   'the creeping sense of embarrassment that everyone knows something about you but you can’t quite place what it is',
	     'the person you first told your deepest secret to', 'the concept of dreams', 
	    'the sharpest nail in the box', 'the ever encroaching hand of Facebook',
	     'that same punk kid you see at all the shows you used to go to sitting in a coffee shop',
	     ' the person you hurt the most', 'a literal dumpster fire',' the friend you lost contact with due to time and circumstance',
	       'an ice storm', 'the person whose life you altered for the better', 'the person you left with things unsaid to',
	        'a whirlwind', 'a monster made of your greatest fears', 'the fading sense of control you have on your life', 
	        'a raccoon sitting at your window too scared to go up or down your neighbours drainpipe',
	          'your childhood pet',
	           'the chickens you hatched in kindergarten', 'a hangnail', 'all of the unanswered emails sitting in your inbox',
	            'a scene kid straight out of 2005',
	            'all known human knowledge', 'someone you fucked when you were 19 and didn’t know better', 
	            'the girl you kissed in middle school',' that woman sitting across from you on the Yonge Line', 
	            'the guy who plays music on his phone on the TTC', 'John Tory braving the TTC',
	             'a pounding headache', 'a gentle touch from a stranger',' pervasive toxic masculinity',
	             'a Facebook event you’re interested in but will never go to', 'a baby koala', 
	             'tuning into a conversation at an inopportune time', 
	              'a very disgruntled cat dress as a wizard', 
	              'a detailed blueprint of the room you first thought of your own mortality in', 
	              'those leftovers you kept saying you were going to eat for lunch until it grew so much mold developed sentience and you were forced to kill it', 
	              'the vague memory of your favourite meal', 'that asshole who always brings his friend to your apartment without asking',
	               'a squirrel suddenly stopped in the middle the road and can’t make up it’s mind where it should go',
	                'an uncomfortably passive aggressive facebook post vaguely directed at you', 'the broken ipod in your drawer',
	                 'a frayed shoelace', 'a ball of twine', 'the CD case that held your prized collection before you got an iPod', 
	                 'a mouldy peach',' The Mouldy Peaches', 'the box of stuff you keep moving with but never unpack', 
	                 'the pile of things you mean to return to people but never get around to', 
	                 '52 jokers', 'an incredibly expensive bottle of olive oil', 
	                 'a 3D printed yoda head', 'your jar full of depleted batteries', 
	                 'an old man offering you a sword', 'a couch which may of may not have bedbugs', 'a single, non standard screw', 
	                 'the best game of pinball you’ve ever played', 'someone you thought youd never see again', 
	                 'the boundlessness of the eternal void', 'entirely formless fear', 'literal garbage', 
	                 'the inevitable heat death of the universe', 'the reaching hand of Satan',
	                 'happiness', 'being forever at arms length', 'an Internet of Things thing', 
	                 'a rabid dog watching you from your peripheral vision',' a tall stranger wearing loafers',
	                 'a cursed sewing machine', 'a cold one with the boys', 
	                 'a counter counting down an explosion to the experimental lab you’ve been trapped in', 
	                 'a sexual encounter with a gentle stranger', 'a fight to the death', 
	                 'someone who pronounces it jif', 
	                 'a woman attempting to get a chicken bone out of her dog’s mouth', 'fiddleheads',
	                 'a piece of the Berlin Wall', 'a vial filled with dirt from an unknown location',' a vial filled with fresh blood', 
	                 'a jar filled with the dying breath of a stranger ', 'a lost credit card from a newly departed lover, lodged between your couch cushions', 
	                 'a warm cup of tea', 'human teeth','a childhood memento',
	                  'a mickey of Fireball', 'a trip to the bar alone', 
	                  'a chip of your gravestone handed to you by a time traveller claiming to be your descendant',' an old pair of socks', 
	                   'a mason jar of apparently glacier water', 'a handful of cranberries', 
	                  'a crumple transfer from the Queen streetcar that you tried to pass off as valid at least once before' 
],
	['But the truth will never escape us', ' I should relapse into capitalism', 
	'I feel comfortable in my corporial being', 'I desire anything beyond my human form', 
	'If I blame all of my problems on the generation following me I can avoid the ever growing pit inside of me', 
	'I should write a letter to my local representative about how their policies have affected me for the better', 
	'A walk around the block is an easy way to ignore my human suffering', 
	'If I buy enough plants maybe someday I wont feel like everything I touch dies', 
	'I should demand a raise from my boss', 'If I take enough stimulants Ill finally be able to get all that work done',
	 'At least everyone is as lost in their humanity as I am', 'Birds are pretty neat', 'My mother might have been right about that idiom she kept repeating', 
	 'Dogs are pretty cool', 'I should like to walk into the sea, I desire sustenance', 'If everyone communicated in song wed probably all be more forgiving of each others faults', 
	 'I can really see myself becoming the \'Family Friend\' that came by every 5 years growing up',
	 'where did I put that again?', 'All interpersonal relationships are relentlessly complex',
	 'My dirt collection can be buried with me when I die', 'I should clear my browser history', 'Eating is living', 
	 'How don\’t I just fall up into the nothingness of space that is constantly sitting precariously above me', 
	 'If I fill my time with distractions the horror of the inevitable void won\’t fill me',
	 'I can\'t stop thinking deeply about existential dread',
	 'I should try a new sandwich place for lunch tomorrow', 'I should call my friend, but I probably wont', 
	 'All of my friends have too many, or not enough, children',
	 'I should reach out to those I have hurt before and apologize for my behaviour', 
	 'I should start a collection of gravel', 'I should start a collection of toe nail clippings', 
	 'I hope my employer doesnt find my old MySpace', 'People in country songs have poor conflict resolution tactics',
	 'I should login to my old Neopets account', 'I should use a map of Paris to navigate the all cities', 
	 'I should take action to better the world for those around me', 'I should take a bath and drink a glass of wine', 
	 'I should yell angrily at country music trying to solve their problems instead of my own', 'I should buy new socks',
	  'I should watch the sunset and wonder how in the world there can be so much beauty around me', 
	  'I am grateful for what I have', 'That cloud looks a lot like a dog', 'do I have enough change for the subway?',
	  'Did I turn off the stove?', 'what was my last meaningful interaction?', 'when is the last time I flossed?',
	  ]
];